name: code_cyprus_app
description: Code Cyprus cross-platform client app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+15

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/http
  http: ^1.2.0

  # https://pub.dev/packages/bubble
  bubble: ^1.2.1

  # https://pub.dev/packages/email_validator
  email_validator: ^2.1.17

  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.2

  # https://pub.dev/packages/dotted_decoration
  dotted_decoration: ^2.0.0

  # https://pub.dev/packages/location
  location: ^5.0.3

  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^5.0.1

  # https://pub.dev/packages/flutter_barcode_scanner
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_html
  flutter_html: ^3.0.0-beta.2

  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.4

  # https://pub.dev/packages/intl
  intl: ^0.19.0

flutter_icons:
  android: true
  ios: true
  image_path: 'icons/launcher.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/waving.gif
    - images/popcorn.gif
    - images/fly.gif
    - images/sleepy.gif
    - images/hi5.gif
    - images/faceslap.gif
    - images/drums.gif
    - images/pirate.png
